// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDK6dPenh3xEFOdit3kaN1WsXJjYdONS0U',
    appId: '1:281400763694:web:63286b060c827f329286bf',
    messagingSenderId: '281400763694',
    projectId: 'crimewatch-15ff3',
    authDomain: 'crimewatch-15ff3.firebaseapp.com',
    storageBucket: 'crimewatch-15ff3.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBYb6SHsb5ghm7e-WtHOkZAj6re5_oZqwA',
    appId: '1:281400763694:android:93bf6882e723a9f39286bf',
    messagingSenderId: '281400763694',
    projectId: 'crimewatch-15ff3',
    storageBucket: 'crimewatch-15ff3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAk1Y8TBRKaDZYFOvlIwVJVEVwHd8CCAn8',
    appId: '1:281400763694:ios:dbc0c0f33931c8159286bf',
    messagingSenderId: '281400763694',
    projectId: 'crimewatch-15ff3',
    storageBucket: 'crimewatch-15ff3.firebasestorage.app',
    iosBundleId: 'com.example.crimewatch',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAk1Y8TBRKaDZYFOvlIwVJVEVwHd8CCAn8',
    appId: '1:281400763694:ios:dbc0c0f33931c8159286bf',
    messagingSenderId: '281400763694',
    projectId: 'crimewatch-15ff3',
    storageBucket: 'crimewatch-15ff3.firebasestorage.app',
    iosBundleId: 'com.example.crimewatch',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDK6dPenh3xEFOdit3kaN1WsXJjYdONS0U',
    appId: '1:281400763694:web:d49d9a0c4a6f92ba9286bf',
    messagingSenderId: '281400763694',
    projectId: 'crimewatch-15ff3',
    authDomain: 'crimewatch-15ff3.firebaseapp.com',
    storageBucket: 'crimewatch-15ff3.firebasestorage.app',
  );
}
